<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.mule.extensions</groupId>
		<artifactId>mule-modules-parent</artifactId>
		<version>1.9.0</version>
	</parent>

	<groupId>8d624bf1-5cd5-455e-94ea-6f2ba716a0ed</groupId>
	<artifactId>api-error-handler</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>mule-extension</packaging>

	<name>API Error Handler</name>
	<description>Provides standard REST API error responses</description>

	<properties>
		<scm.connection>scm:git:git@github.com:brunosouzas/mulesoft-error-handler-plugin.git</scm.connection>
		<scm.developerConnection>${scm.connection}</scm.developerConnection>
		<scm.url>https://github.com/brunosouzas/mulesoft-error-handler-plugin</scm.url>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<!-- mule.version is mandatory for mule-extension projects and must be hardcoded -->
		<mule.version>4.9.1</mule.version>
		<mule.extensions.maven.plugin.version>1.9.0</mule.extensions.maven.plugin.version>
		<exchange.mule.maven.plugin.version>0.0.23</exchange.mule.maven.plugin.version>
		<maven.release.plugin.version>3.3.1</maven.release.plugin.version>
		<mule.app.classifier>mule-plugin</mule.app.classifier>
		<java.version>17</java.version>
	</properties>

	<scm>
		<connection>${scm.connection}</connection>
		<developerConnection>${scm.developerConnection}</developerConnection>
		<url>${scm.url}</url>
		<tag>HEAD</tag>
	</scm>

	<dependencies>
		<!--Needed
		to discover the 'xml-based' XmlExtensionLoader for smart connectors -->
		<dependency>
			<groupId>org.mule.runtime</groupId>
			<artifactId>mule-module-extensions-xml-support</artifactId>
			<version>${mule.version}</version>
			<scope>provided</scope>
		</dependency>
		<!-- DataWeave -->
		<dependency>
			<groupId>com.mulesoft.mule.runtime.modules</groupId>
			<artifactId>mule-module-spring-config-ee</artifactId>
			<version>${mule.version}</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.mule.runtime.plugins</groupId>
				<artifactId>mule-extensions-maven-plugin</artifactId>
				<version>${mule.extensions.maven.plugin.version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.mule.tools.maven</groupId>
				<artifactId>exchange-mule-maven-plugin</artifactId>
				<version>${exchange.mule.maven.plugin.version}</version>
				<executions>
					<execution>
						<id>validate</id>
						<phase>validate</phase>
						<goals>
							<goal>exchange-pre-deploy</goal>
						</goals>
					</execution>
					<execution>
						<id>deploy</id>
						<phase>deploy</phase>
						<goals>
							<goal>exchange-deploy</goal>
						</goals>
					</execution>
				</executions>
				<inherited>false</inherited>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-release-plugin</artifactId>
				<version>${maven.release.plugin.version}</version>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange V3</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>mule-releases</id>
			<name>MuleSoft Releases Repository</name>
			<url>https://repository.mulesoft.org/releases/</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>mule-ee-repository</id>
			<name>MuleSoft Enterprise Repository</name>
			<url>https://repository.mulesoft.org/nexus-ee/content/repositories/releases-ee/</url>
			<layout>default</layout>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>mule-releases</id>
			<name>MuleSoft Releases Repository</name>
			<layout>default</layout>
			<url>https://repository.mulesoft.org/releases/</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<repository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</repository>
		<snapshotRepository>
			<id>anypoint-exchange-v3</id>
			<name>Anypoint Exchange Snapshots</name>
			<url>https://maven.anypoint.mulesoft.com/api/v3/organizations/${project.groupId}/maven</url>
			<layout>default</layout>
		</snapshotRepository>
	</distributionManagement>

</project>
